### PR TITLE
feat: not resolve executables that are already passed as absolute paths

### PR DESCRIPTION
**Pull request by AndrewBarba**
- Detect an absolute executable path
- Properly set environment

### CODE REVIEW

**Review by pepicrft — APPROVED** [review]
@AndrewBarba thanks for fixing this 🙏🏼. Do you mind adding an integration tests that covers this scenario and resolving the conflicts? We can merge right after if CI is green.

**Comment by pepicrft** [comment]
@all-contributors add @AndrewBarba for code

**Comment by AndrewBarba** [comment]
@pepicrft All set! Thanks so much

**Comment by pepicrft** [comment]
Thanks a lot @AndrewBarba 🙏🏼

**Pull request merged**
